export {
  AddPageActionSchema,
  ApplicationActionSchema,
  CreateGroupActionSchema,
  DeleteObjectActionSchema,
  DeletePageActionSchema,
  DuplicateObjectActionSchema,
  DuplicatePageActionSchema,
  FrameUSchema,
  IconObjectInsertSpecSchema,
  ImageObjectInsertSpecSchema,
  InsertObjectActionSchema,
  InsertPageTemplateActionSchema,
  InsertedTableColumnPropertiesSchema,
  InsertedTableRowPropertiesSchema,
  LineObjectInsertSpecSchema,
  MoveObjectActionSchema,
  ObjectInsertSpecSchema,
  RenameDocumentActionSchema,
  ReorderObjectActionSchema,
  ReorderPageActionSchema,
  ReplaceImageActionSchema,
  ResizeObjectActionSchema,
  TableFitHeightActionSchema,
  TableFitHeightTypographySchema,
  SetTextContentActionSchema,
  ShapeObjectInsertSpecSchema,
  TableObjectInsertSpecSchema,
  TableAxisInsertActionSchema,
  TableAxisRemoveActionSchema,
  TableCellsMergeActionSchema,
  TableCellUnmergeActionSchema,
  TableCellContentInputSchema,
  TableCellSetContentActionSchema,
  TableBulkMarkerReferenceSchema,
  TableBulkExpectedTopologySchema,
  TableBulkCellContentInputSchema,
  TableBulkContentTargetSchema,
  TableLegendCreateInputSchema,
  TableCellsSetContentsActionSchema,
  TableLegendCreateActionSchema,
  TableLegendUpdateActionSchema,
  TableLegendRemoveActionSchema,
  CellStylePatchSchema,
  CellPropertyPatchSchema,
  TableCellPropertyTargetSchema,
  TableCellSetPropertiesActionSchema,
  TableStyleSetBaseActionSchema,
  TableStyleSetRowRoleActionSchema,
  TableStyleTargetSchema,
  TableRowsSetStyleActionSchema,
  TableColumnsSetStyleActionSchema,
  TablePresetIdSchema,
  TablePresetPresentationSnapshotSchema,
  TablePresetApplyActionSchema,
  TableRowRoleSchema,
  TableRowHeightPolicyUSchema,
  TableRowPropertyTargetSchema,
  TableRowsSetPropertiesActionSchema,
  TableColumnWidthUSchema,
  TableColumnPropertyTargetSchema,
  TableColumnsSetPropertiesActionSchema,
  TableAxisReorderActionSchema,
  TextObjectInsertSpecSchema,
  UngroupActionSchema,
} from './contracts';
export type {
  ActionMetadata,
  ApplicationAction,
  ApplicationActionFailure,
  ApplicationActionResult,
  ApplicationActionSuccess,
  ApplicationActionType,
  ApplicationError,
  ApplicationErrorCode,
  ApplicationExecutionContext,
  FrameU,
  IdGenerator,
  ObjectInsertSpec,
  TableCellContentInput,
  TableBulkCellContentInput,
  TableBulkExpectedTopology,
  TableBulkContentTarget,
  TableLegendCreateInput,
  TableFitHeightTypography,
  CellStylePatch,
  CellPropertyPatch,
  TableCellPropertyTarget,
  TableStyleTarget,
  TablePresetId,
  TablePresetPresentationSnapshot,
  TableRowHeightPolicyU,
  TableRowPropertyTarget,
  TableColumnWidthU,
  TableColumnPropertyTarget,
} from './contracts';
export {
  ApplicationDocumentError,
  authoredStructuralIdentityIds,
  canonicalIdentityIds,
  canonicalObjectIdentityIds,
  allocateFreshCanonicalId,
  CatalogCloneService,
  createCatalogDocument,
  findObjectLocation,
  instantiatePageWithFreshIds,
  parseCanonicalDocument,
} from './document';
export type {
  CatalogCloneOptions,
  ObjectLocation,
  ObjectInstantiationSeed,
  LeafObjectInstantiationSeed,
  GroupObjectInstantiationSeed,
} from './document';
export {
  plainRichTextSemanticallyEquals,
  projectEditableRichText,
  reconcileEditableRichText,
  richTextEquals,
  richTextSemanticFingerprint,
  richTextSemanticallyEquals,
} from './text-editing';
export { executeApplicationAction } from './execute';
export type { ApplicationExecutionDependencies } from './execute';
export {
  TABLE_PRESETS,
  materializeTablePreset,
  tablePresetPresentationSnapshot,
} from './table-preset-registry';
export type { TablePresetDefinition } from './table-preset-registry';
export { createDocumentSession } from './session';
export type { DocumentSession, DocumentSessionSnapshot, HistoryResult } from './session';
export {
  createStaticPageTemplateRegistry,
  parsePageTemplateDefinition,
  PageTemplateDefinitionError,
} from './template-registry';
export type {
  PageTemplateDefinition,
  PageTemplateDefinitionIssue,
  PageTemplateRegistry,
} from './template-registry';
