'use client'
import { useState } from 'react'
import { useShallow } from 'zustand/react/shallow'
import { Plus,Search,X,Unlink,Package,Layers,Palette } from 'lucide-react'
import { useEditorStore } from '../../features/editor/editor-store'
import { PageManager } from '../pages/page-manager'
import { PresetManager } from '../presets/preset-manager'
export function Sidebar({isOpenMobile=false,onCloseMobile}: {isOpenMobile?:boolean;onCloseMobile?:()=>void}){
  const [tab,setTab]=useState<'products'|'pages'|'presets'>('products')
  const [search,setSearch]=useState('')
  const {products,selected,currentUser,localMode}=useEditorStore(useShallow(s=>({products:s.products,selected:s.selectedProductId,currentUser:s.currentUser,localMode:s.localMode})))
  const editable=localMode||!!currentUser&&currentUser.role!=='viewer'
  const add=()=>{const s=useEditorStore.getState();s.addProduct({catalog_id:s.catalog?.id??'',sku:'NOVO-'+crypto.randomUUID().slice(0,6).toUpperCase(),name:'Novo produto',family:'',status:'draft',sort_order:products.length,data:{marketing:{title:'',overview:'',images:[],features:[]},specs:[],electrical:[],general:[],accessories:[]}})}
  return <>{isOpenMobile&&<button aria-label="Fechar navegação" className="fixed inset-0 z-30 bg-black/40 lg:hidden" onClick={onCloseMobile}/>}<aside className={'no-print w-64 shrink-0 flex-col border-r border-slate-200 bg-white '+(isOpenMobile?'fixed inset-y-0 left-0 z-40 flex':'hidden lg:flex')}>
    <div className="flex items-center justify-between border-b p-3"><strong className="text-xs text-slate-500">ESTRUTURA DO DOCUMENTO</strong><button onClick={onCloseMobile} className="lg:hidden" aria-label="Fechar menu"><X size={17}/></button></div>
    <nav className="grid grid-cols-3 border-b">{[{id:'products',label:'Produtos',icon:Package},{id:'pages',label:'Páginas',icon:Layers},{id:'presets',label:'Templates',icon:Palette}].map(t=><button key={t.id} onClick={()=>setTab(t.id as typeof tab)} className={'flex flex-col items-center gap-1 px-1 py-3 text-[11px] '+(tab===t.id?'bg-blue-50 font-semibold text-blue-900':'text-slate-500')}><t.icon size={16}/>{t.label}</button>)}</nav>
    <div className="flex min-h-0 flex-1 flex-col overflow-auto">{tab==='products'?<><div className="relative m-3"><Search size={14} className="absolute left-2 top-2.5 text-slate-400"/><input aria-label="Filtrar produtos do documento" value={search} onChange={e=>setSearch(e.target.value)} placeholder="SKU ou nome" className="w-full rounded border border-slate-200 py-2 pl-7 pr-2 text-xs"/></div><button disabled={!editable} onClick={add} className="mx-3 mb-3 flex items-center justify-center gap-1 rounded border border-slate-200 py-2 text-xs disabled:opacity-40"><Plus size={14}/>Novo produto</button><div className="space-y-1 px-2">{products.filter(p=>(p.sku+' '+p.name).toLowerCase().includes(search.toLowerCase())).map(p=><div key={p.id} className={'flex rounded-md border '+(selected===p.id?'border-blue-200 bg-blue-50':'border-transparent hover:bg-slate-50')}><button className="min-w-0 flex-1 p-3 text-left" onClick={()=>{useEditorStore.getState().setSelectedProductId(p.id);onCloseMobile?.()}}><strong className="block truncate text-xs">{p.sku}</strong><span className="mt-1 block truncate text-[11px] text-slate-500">{p.name}</span><span className="mt-1 block text-[10px] text-slate-400">{p.family||'Família não informada'}</span></button><button disabled={!editable} onClick={()=>useEditorStore.getState().deleteProduct(p.id)} aria-label={'Desvincular '+p.sku} title="Remover deste documento (o cadastro é preservado)" className="p-2 text-slate-400 hover:text-red-700 disabled:opacity-30"><Unlink size={14}/></button></div>)}</div>{!products.length&&<p className="p-4 text-center text-xs text-slate-500">Vincule produtos pelo dashboard ou crie um cadastro.</p>}</>:tab==='pages'?<PageManager/>:<PresetManager/>}</div>
    <p className="border-t p-3 text-[10px] text-slate-500">{localMode?'Modo local · sem acesso à equipe':currentUser?'Sessão autenticada · '+currentUser.role:'Entre para acessar a equipe'}</p>
  </aside></>
}
