import { useRef, useState, type PointerEvent as PE } from 'react';
import { ArrowLeft, Undo2, Redo2, Eye, Download, MousePointer2, Type, ImagePlus, Table2, Shapes, Minus, Blocks, LayoutTemplate, FolderOpen, Plus, Copy, Trash2, ChevronDown, Sparkles, Grip, PanelLeftClose } from 'lucide-react';
import { TableCanvas, TableControls, type Range } from './TableUI';
import { ColorControl } from './ColorControl';
import { initial, make, table, cover, uid, Product, type Item, type Page } from './fixtures';

export function Editor(){
 const [pages,setPages]=useState(initial),[pageIndex,setPageIndex]=useState(1),[selection,setSelection]=useState<string[]>([]),[panel,setPanel]=useState('Páginas'),[collapsed,setCollapsed]=useState(false);
 const [zoom,setZoom]=useState(Math.min(1,(window.innerHeight-275)/842)),[margin,setMargin]=useState('hybrid'),[snap,setSnap]=useState(true),[dragging,setDragging]=useState(false),[guide,setGuide]=useState(false);
 const [past,setPast]=useState<Page[][]>([]),[future,setFuture]=useState<Page[][]>([]),[modal,setModal]=useState(''),[preview,setPreview]=useState(false),[message,setMessage]=useState('Pronto para editar'),[editing,setEditing]=useState('');
 const [catalog,setCatalog]=useState('TA-25N · Catálogo técnico'),[components,setComponents]=useState<Item[][]>([]);
 const [range,setRange]=useState<Range|null>(null),[presets,setPresets]=useState<Partial<Item>[]>([]),[toolbar,setToolbar]=useState(true);
 const documentColors=[...new Set(pages.flatMap(p=>p.objects.flatMap(o=>[o.fill,o.color,...Object.values(o.cells||{}).flatMap(c=>[c.fill||'#ffffff',c.color||'#16374b'])])))];
 const clip=useRef<Item[]>([]), page=pages[Math.min(pageIndex,pages.length-1)], selected=page.objects.find(o=>o.id===selection[0]);
 const save=(next:Page[])=>{setPast(p=>[...p,structuredClone(pages)]);setFuture([]);setPages(next);setMessage('Alteração guardada nesta sessão');};
 const change=(fn:(p:Page[])=>void)=>{const n=structuredClone(pages);fn(n);save(n);};
 const patch=(id:string,values:Partial<Item>)=>change(p=>{Object.assign(p[pageIndex].objects.find(o=>o.id===id)!,values);});
 const undo=()=>{if(!past.length)return;setFuture(f=>[structuredClone(pages),...f]);setPages(past[past.length-1]);setPast(p=>p.slice(0,-1));setSelection([]);setMessage('Alteração desfeita');};
 const redo=()=>{if(!future.length)return;setPast(p=>[...p,structuredClone(pages)]);setPages(future[0]);setFuture(f=>f.slice(1));setSelection([]);setMessage('Alteração refeita');};
 const insert=(o:Item)=>{change(p=>p[pageIndex].objects.push(o));setSelection([o.id]);setPanel('Páginas');};
 const duplicate=()=>{const list=page.objects.filter(o=>selection.includes(o.id)).map(o=>({...structuredClone(o),id:uid(),x:o.x+16,y:o.y+16}));change(p=>p[pageIndex].objects.push(...list));setSelection(list.map(o=>o.id));};
 const remove=()=>{change(p=>{p[pageIndex].objects=p[pageIndex].objects.filter(o=>!selection.includes(o.id));});setSelection([]);};
 const select=(o:Item,shift=false)=>{setSelection(shift?selection.includes(o.id)?selection.filter(id=>id!==o.id):[...selection,o.id]:[o.id]);};
 const move=(e:PE,o:Item,resize=false)=>{
  if(preview||editing||e.button!==0||(e.target as HTMLElement).closest('button,input,[contenteditable="true"]'))return;
  e.stopPropagation();select(o,e.shiftKey);if(e.shiftKey)return;
  const el=e.currentTarget as HTMLElement;
  const start=structuredClone(pages),x=e.clientX,y=e.clientY;let latest=start,moved=false;
  const ids=selection.includes(o.id)?selection:[o.id];
  const onmove=(ev:PointerEvent)=>{const dx=(ev.clientX-x)/zoom,dy=(ev.clientY-y)/zoom;if(Math.abs(dx)+Math.abs(dy)<2)return;moved=true;el.setPointerCapture(e.pointerId);setDragging(true);
   latest=structuredClone(start);let aligned=false;
   latest[pageIndex].objects.filter(a=>ids.includes(a.id)).forEach(a=>{
    if(resize){a.w=Math.max(30,a.w+dx);a.h=Math.max(18,a.h+dy);}else{a.x+=dx;a.y+=dy;
     if(snap&&!ev.altKey){for(const target of [36,48,595/2-a.w/2,595-36-a.w])if(Math.abs(a.x-target)<6){a.x=target;aligned=true;}for(const target of [36,48,842/2-a.h/2,842-36-a.h])if(Math.abs(a.y-target)<6){a.y=target;aligned=true;}}
    }
   });setGuide(aligned);setPages(latest);
  };
  const end=()=>{el.removeEventListener('pointermove',onmove);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);setDragging(false);setGuide(false);if(moved){setPast(p=>[...p,start]);setFuture([]);setMessage(resize?'Tamanho ajustado':'Objeto movido');}};
  el.addEventListener('pointermove',onmove);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);
 };
 const warnings=(o:Item)=>{const a:string[]=[];if(o.x<0||o.y<0||o.x+o.w>595||o.y+o.h>842)a.push('Parte deste objeto está fora da página.');else if(!o.bleed&&(o.x<36||o.y<36||o.x+o.w>559||o.y+o.h>806))a.push('Próximo à borda. Confira a margem de segurança.');if(o.kind==='text'&&o.text.split('\n').reduce((s,l)=>s+Math.max(1,Math.ceil(l.length*o.size*.52/o.w)),0)*o.size*(o.leading||1.25)>o.h)a.push('Parte deste texto não cabe no quadro.');if(o.kind==='table'&&((o.rows?.length||0)*(o.size*1.3+2*(o.padding??10))+(o.title?36:0)+(o.group?38:0)+(o.section?28:0)+(o.note?26:0)+(o.footnote?26:0)>o.h))a.push('Parte desta tabela não cabe no quadro. Aumente o quadro ou reduza o conteúdo.');return a;};
 const allWarnings=pages.flatMap((p,i)=>p.objects.flatMap(o=>warnings(o).map(t=>({page:i,id:o.id,t}))));
 const tools=[['Selecionar',MousePointer2],['Texto',Type],['Imagem',ImagePlus],['Tabela',Table2],['Formas',Shapes],['Linha',Minus],['Componentes',Blocks],['Modelos',LayoutTemplate],['Arquivos',FolderOpen]] as const;
 const handleTool=(name:string)=>{if(name==='Texto')insert(make('text'));else if(name==='Tabela')insert(table());else if(name==='Formas')insert(make('shape',{y:330,h:80}));else if(name==='Linha')insert(make('line',{y:410,h:3}));else if(name==='Selecionar'){setSelection([]);setPanel('Páginas');}else setPanel(name);};
 const addPage=()=>{change(p=>p.push({id:uid(),name:'Nova página',objects:[]}));setPageIndex(pages.length);setSelection([]);};
 const component=(name:string)=>{const bg=make('shape',{name,x:48,y:340,w:490,h:76,fill:'#123e59'}),txt=make('text',{name:name+' · texto',x:65,y:361,w:450,h:34,text:name,size:20,color:'#ffffff',bold:true});change(p=>p[pageIndex].objects.push(bg,txt));setSelection([bg.id,txt.id]);};
 const onKey=(e:React.KeyboardEvent)=>{if(preview)return;if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable="true"]'))return;
 if((e.ctrlKey||e.metaKey)&&['z','y','d','c','v'].includes(e.key.toLowerCase())){e.preventDefault();const k=e.key.toLowerCase();if(k==='z')e.shiftKey?redo():undo();if(k==='y')redo();if(k==='d')duplicate();if(k==='c')clip.current=structuredClone(page.objects.filter(o=>selection.includes(o.id)));if(k==='v'){const list=clip.current.map(o=>({...o,id:uid(),x:o.x+20,y:o.y+20}));change(p=>p[pageIndex].objects.push(...list));setSelection(list.map(o=>o.id));}return;}
 if(e.key==='Delete'&&selection.length){e.preventDefault();remove();}
 if(e.key==='Escape'){setSelection([]);setEditing('');setModal('');}
 if(e.key.startsWith('Arrow')&&selection.length){e.preventDefault();change(p=>p[pageIndex].objects.filter(o=>selection.includes(o.id)).forEach(o=>{const d=e.shiftKey?10:1;o.x+=e.key==='ArrowRight'?d:e.key==='ArrowLeft'?-d:0;o.y+=e.key==='ArrowDown'?d:e.key==='ArrowUp'?-d:0;}));}
 };
 const objectView=(o:Item,mini=false)=><>{o.kind==='text'?<div className="text-content" ref={el=>{if(el&&editing===o.id&&document.activeElement!==el)el.focus();}} contentEditable={!mini&&editing===o.id} suppressContentEditableWarning role={!mini?'textbox':undefined} aria-label={!mini?o.name:undefined} onDoubleClick={()=>!preview&&!mini&&setEditing(o.id)} onBlur={e=>{if(editing===o.id){const text=e.currentTarget.innerText;setEditing('');if(text!==o.text)patch(o.id,{text});}}} style={{fontSize:o.size,fontWeight:o.bold?700:400,fontStyle:o.italic?'italic':'normal',fontFamily:o.font||'Arial',lineHeight:o.leading||1.25,textAlign:o.align||'left',color:o.color}}>{o.text}</div>:o.kind==='image'?<div className="product-frame" style={{background:o.alternate?'#d7e8e8':'#f2f5f6',borderRadius:o.radius||0,opacity:o.opacity??1}}><div style={{height:'100%',transform:`scale(${o.fit==='cover'?1.5:1}) translateX(${o.crop||0}%)`}}><Product alternate={o.alternate}/></div></div>:o.kind==='table'?<TableCanvas o={o} range={range} setRange={setRange} patch={patch} select={()=>select(o)} zoom={zoom} mini={mini||preview} active={!mini&&!preview&&selection.includes(o.id)}/>:<div style={{height:'100%',background:o.fill,borderRadius:o.radius||0}}/>}</>;
 return <div className={`editor ${collapsed?'collapsed':''} ${preview?'preview':''}`} onKeyDown={onKey} tabIndex={-1}>
 <header className="topbar"><button onClick={()=>setModal('Catálogos')}><ArrowLeft size={17}/> Catálogos</button><span className="divider"/><input aria-label="Nome do catálogo" value={catalog} onChange={e=>setCatalog(e.target.value)}/><span className="save-status">● Na sessão <small>LAB</small></span><div className="spacer"/><button title="Desfazer · Ctrl+Z" aria-label="Desfazer" disabled={!past.length} onClick={undo}><Undo2 size={18}/></button><button title="Refazer · Ctrl+Y" aria-label="Refazer" disabled={!future.length} onClick={redo}><Redo2 size={18}/></button><span className="divider"/><button onClick={()=>setPreview(!preview)}><Eye size={17}/>{preview?'Voltar à edição':'Prévia'}</button><button onClick={()=>setModal('Traduzir')}>Traduzir</button><button className="share" onClick={()=>setModal('Compartilhar')}>Compartilhar</button><button className="primary" onClick={()=>setModal('Revisar e exportar')}><Download size={16}/>Exportar</button></header>
 <nav className="rail">{tools.map(([name,Icon])=><button key={name} className={panel===name?'active':''} onClick={()=>handleTool(name)} title={name}><Icon size={22}/><span>{name}</span></button>)}<div className="spacer"/><button onClick={()=>setModal('Perguntar à IA')}><Sparkles size={20}/><span>IA</span></button></nav>
 <aside className="sidebar"><div className="panel-heading"><strong>{panel}</strong><button aria-label="Recolher páginas" onClick={()=>setCollapsed(!collapsed)}><PanelLeftClose size={17}/></button></div><div className="sidebar-body">
 {panel==='Páginas'?<>{pages.map((p,i)=><button aria-label={`Página ${i+1}: ${p.name}`} className={`page-card ${pageIndex===i?'active':''}`} key={p.id} onClick={()=>{setPageIndex(i);setSelection([]);}}><div className="thumbnail" aria-hidden="true">{p.objects.map(o=><div key={o.id} style={{position:'absolute',left:o.x,top:o.y,width:o.w,height:o.h,overflow:'hidden'}}>{objectView(o,true)}</div>)}</div><span>{String(i+1).padStart(2,'0')} · {p.name}</span>{p.objects.some(o=>warnings(o).length>0)&&<b className="thumb-warning">!</b>}</button>)}<button className="add-page" onClick={addPage}><Plus size={16}/>Adicionar página</button></>:panel==='Imagem'||panel==='Arquivos'?<><p className="hint">Imagens do produto</p><button className="asset-card" onClick={()=>insert(make('image',{y:190,w:290,h:230}))}><Product/><b>Calibrador · demonstração</b><span>Inserir na página</span></button><p className="hint">Ilustração de referência. Substitua pela imagem aprovada no produto final.</p></>:panel==='Modelos'?<><button className="template-card" onClick={()=>{change(p=>p.push(cover()));setPageIndex(pages.length);setSelection([]);}}>PRESYS<br/><b>Capa técnica</b><span>Adicionar como página editável →</span></button><p className="hint">Cada texto, imagem e forma pode ser editado.</p></>:<><p className="hint">Blocos prontos para personalizar</p>{['Cabeçalho PRESYS','Banner técnico','Rodapé de contato','Destaque de recurso'].map(n=><button className="component-card" key={n} onClick={()=>component(n)}>{n}<Plus size={15}/></button>)}{components.map((list,i)=><button key={i} className="component-card" onClick={()=>{const copy=list.map(o=>({...structuredClone(o),id:uid(),y:o.y+25}));change(p=>p[pageIndex].objects.push(...copy));setSelection(copy.map(o=>o.id));}}>Meu componente {i+1}<Plus size={15}/></button>)}</>}
 </div><div className="sidebar-bottom"><span>PRESYS</span><small>Editor de catálogos</small></div></aside>
 <main className="workspace"><div className="workspace-heading"><button className="reopen" onClick={()=>setCollapsed(false)}>Páginas</button><span>{String(pageIndex+1).padStart(2,'0')} / {pages.length} <b>{page.name}</b></span><span>A4 · 210 × 297 mm</span></div>
 <div className="contextbar">{selected?<><span className="selection-label">{selection.length>1?`${selection.length} objetos`:selected.name}</span><button onClick={duplicate}><Copy size={15}/>Duplicar</button><button onClick={remove}><Trash2 size={15}/>Excluir</button><button onClick={()=>{setComponents(c=>[...c,structuredClone(page.objects.filter(o=>selection.includes(o.id)))]);setPanel('Componentes');setMessage('Componente disponível nesta sessão');}}>Salvar componente</button><span className="context-hint">{selected.kind==='text'?'Duplo clique para editar':selected.kind==='table'?'Duplo clique edita a célula':'Arraste para mover'}</span>{selected.kind==='table'&&toolbar&&<TableControls o={selected} range={range} setRange={setRange} patch={patch} documentColors={documentColors} onSave={()=>{}}/>}</>:<span className="context-hint">Selecione um objeto para editar • Arraste para mover • Shift + clique para selecionar vários</span>}</div>
 <div className="canvas-scroll" onPointerDown={e=>{if(e.target===e.currentTarget)setSelection([]);}}><div className="page-wrap" style={{width:595*zoom,height:842*zoom}}><div className="paper" style={{transform:`scale(${zoom})`}} onPointerDown={e=>{if(e.target===e.currentTarget)setSelection([]);}}>
 {!preview&&<div className={`safe-area ${margin} ${margin==='always'||margin==='hybrid'||(margin==='context'&&selection.length)?'visible':''} ${selection.length?'emphasis':''} ${dragging?'moving':''}`}/>}
 {!preview&&guide&&<div className="alignment-guide"/>}
 {page.objects.map(o=><div key={o.id} data-object={o.name} className={`object ${!preview&&selection.includes(o.id)?'selected':''}`} style={{left:o.x,top:o.y,width:o.w,height:o.h}} onPointerDown={e=>move(e,o)} onClick={e=>{e.stopPropagation();}}>
 {objectView(o)}
 {!preview&&selection.includes(o.id)&&<><button className="move-handle" aria-label={`Mover ${o.name}`} onPointerDown={e=>{e.stopPropagation();const target=e.target as HTMLElement;target.blur();move({...e,target:e.currentTarget.parentElement} as PE,o);}}><Grip size={14}/></button><div className="resize-handle" role="button" aria-label={`Redimensionar ${o.name}`} onPointerDown={e=>move(e,o,true)}/></>}
 {!preview&&warnings(o).length>0&&<span className="object-warning" title={warnings(o).join(' ')}>!</span>}
 </div>)}</div></div></div>
 </main>
 <aside className="inspector"><div className="panel-heading"><strong>{selected?selection.length>1?'Seleção múltipla':selected.name:'Página'}</strong><span className="eyebrow">PROPRIEDADES</span></div><div className="inspector-body">
 {selected?<><p className="hint">{selected.kind==='text'?'Edite o conteúdo diretamente na página com um duplo clique.':'Ajuste a seleção. Arraste no papel para posicionar.'}</p>{warnings(selected).map(t=><div className="warning" key={t}>{t}</div>)}
 {selected.kind==='table'&&<><label><input type="checkbox" checked={toolbar} onChange={e=>setToolbar(e.target.checked)}/> Barra rápida da tabela</label><TableControls o={selected} range={range} setRange={setRange} patch={patch} documentColors={documentColors} inspector onSave={()=>{setPresets(p=>[...p,{fill:selected.fill,color:selected.color,size:selected.size,padding:selected.padding,borders:selected.borders}]);setMessage('Estilo de tabela salvo nesta sessão');}}/>{presets.length>0&&<button className="wide" onClick={()=>patch(selected.id,presets[presets.length-1])}>Aplicar meu estilo de tabela</button>}</>}{selected.kind==='text'&&<section><h3>Texto</h3><label>Fonte<select value={selected.font||'Arial'} onChange={e=>patch(selected.id,{font:e.target.value})}><option>Arial</option><option>Georgia</option><option>Verdana</option></select></label><div className="form-row"><label>Tamanho<input type="number" min="8" value={selected.size} onChange={e=>patch(selected.id,{size:+e.target.value})}/></label><button className={selected.bold?'active':''} onClick={()=>patch(selected.id,{bold:!selected.bold})}><b>B</b></button><button className={selected.italic?'active':''} onClick={()=>patch(selected.id,{italic:!selected.italic})}><i>I</i></button></div><label>Alinhamento<select value={selected.align||'left'} onChange={e=>patch(selected.id,{align:e.target.value as Item['align']})}><option value="left">À esquerda</option><option value="center">Centralizado</option><option value="right">À direita</option></select></label><label>Entrelinhas<input type="number" step=".1" min="1" value={selected.leading||1.25} onChange={e=>patch(selected.id,{leading:+e.target.value})}/></label><ColorControl label="Cor do texto" value={selected.color} onChange={color=>patch(selected.id,{color})} documentColors={documentColors}/></section>}
 {selected.kind==='image'&&<section><h3>Imagem</h3><button className="wide" onClick={()=>patch(selected.id,{alternate:!selected.alternate})}>Substituir imagem</button><label>Enquadramento<select value={selected.fit||'contain'} onChange={e=>patch(selected.id,{fit:e.target.value})}><option value="contain">Mostrar imagem inteira</option><option value="cover">Preencher quadro</option></select></label><label>Ajustar recorte<input aria-label="Ajustar recorte" type="range" min="-25" max="25" value={selected.crop||0} onChange={e=>patch(selected.id,{crop:+e.target.value})}/></label><label>Opacidade<input type="range" min=".1" max="1" step=".1" value={selected.opacity??1} onChange={e=>patch(selected.id,{opacity:+e.target.value})}/></label><label>Cantos arredondados<input type="number" min="0" max="100" value={selected.radius||0} onChange={e=>patch(selected.id,{radius:+e.target.value})}/></label></section>}
 {(selected.kind==='shape'||selected.kind==='line')&&<section><h3>Aparência</h3><ColorControl label="Preenchimento" value={selected.fill} onChange={fill=>patch(selected.id,{fill})} documentColors={documentColors}/><label><input type="checkbox" checked={selected.bleed||false} onChange={e=>patch(selected.id,{bleed:e.target.checked})}/> Fundo até a borda</label></section>}
 <details open><summary>Posição e tamanho</summary><div className="form-grid">{(['x','y','w','h'] as const).map((k,i)=><label key={k}>{['X','Y','Largura','Altura'][i]} · mm<input aria-label={['X','Y','Largura','Altura'][i]} type="number" step="1" value={Math.round(selected[k]*210/595)} onChange={e=>patch(selected.id,{[k]:+e.target.value*595/210})}/></label>)}</div><p className="hint">Use as setas para ajustes finos.</p></details><details><summary>Organizar</summary><button className="wide" onClick={()=>change(p=>{const a=p[pageIndex].objects;a.splice(a.findIndex(o=>o.id===selected.id),1);a.push(selected);})}>Trazer para frente</button><button className="wide" onClick={()=>change(p=>{const a=p[pageIndex].objects;a.splice(a.findIndex(o=>o.id===selected.id),1);a.unshift(selected);})}>Enviar para trás</button></details>
 </>:<><section><span className="eyebrow">PRONTA PARA COMPOR</span><h2>Sua página,<br/>do seu jeito.</h2><p className="hint">Adicione texto, imagens e tabelas. Você decide onde cada elemento fica.</p><button className="wide" onClick={()=>setPanel('Modelos')}><LayoutTemplate size={16}/>Usar um modelo</button></section><section><h3>Guia de segurança</h3><p className="hint">Uma referência para proteger o conteúdo no corte e na impressão.</p><label>Mostrar margem<select aria-label="Mostrar margem" value={margin} onChange={e=>setMargin(e.target.value)}><option value="always">A · Sempre visível</option><option value="context">B · Ao selecionar / mover</option><option value="hybrid">Híbrida · Suave em repouso</option></select></label><label><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/> Encaixar nas guias</label><p className="hint">Segure Alt ao arrastar para mover livremente.</p></section><section><h3>Antes de publicar</h3><button className="wide" onClick={()=>setModal('Revisar e exportar')}>{allWarnings.length?allWarnings.length+' avisos para revisar':'Revisar o catálogo'}<ChevronDown size={14}/></button></section></>}
 </div><div className="lab-note">LAB EXPERIMENTAL · Alterações temporárias</div></aside>
 <footer className="statusbar"><span role="status">{message}</span><div className="spacer"/><span>{selection.length?selection.length+' selecionado(s)':'Português · Brasil'}</span><button onClick={()=>setZoom(z=>Math.max(.4,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.5,z+.1))}>+</button><button onClick={()=>setZoom(Math.min(1,(window.innerHeight-275)/842))}>Ajustar página</button></footer>
 {modal&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-label={modal}><button className="close" onClick={()=>setModal('')}>✕</button><span className="eyebrow">PRESYS · CATÁLOGO</span><h2>{modal}</h2>{modal==='Catálogos'?<><p>Seu catálogo de demonstração está aberto nesta sessão.</p><button className="primary" onClick={()=>setModal('')}>Abrir TA-25N</button></>:modal==='Revisar e exportar'?<><p>Confira o catálogo antes de gerar o PDF.</p>{allWarnings.length?allWarnings.map((w,i)=><button className="preflight-row" key={i} onClick={()=>{setPageIndex(w.page);setSelection([w.id]);setModal('');}}>Página {w.page+1} · {w.t} →</button>):<p className="success">Nenhum aviso nesta demonstração.</p>}<button className="primary" disabled>Gerar PDF · disponível no produto final</button><p className="hint">Esta é uma prévia de interação. Nenhum arquivo será publicado.</p></>:modal==='Perguntar à IA'?<><p>O que você gostaria de criar?</p><textarea defaultValue="Crie uma página de especificações para o TA-25N"/><div className="plan"><b>Prévia do plano · demonstração</b><p>1. Adicionar uma página A4<br/>2. Inserir título e imagem do produto<br/>3. Inserir uma tabela de especificações</p></div><button disabled>Aplicar plano · recurso futuro</button></>:<><p>{modal==='Traduzir'?'Escolha o idioma e revise todos os textos, incluindo títulos de tabela e notas.':'Compartilhe uma versão publicada do catálogo.'}</p>{modal==='Traduzir'&&<select aria-label="Idioma"><option>Español</option><option>English</option></select>}<p className="hint">Recurso demonstrativo. Nenhuma operação será executada.</p><button disabled>Disponível no produto final</button></>}</div></div>}
 </div>;
}




